// Generates src/intel/generatedContext.ts from the audited engine-context corpus.
// Embeds long corpus strings as JSON.stringify literals (bulletproof: backticks / ${} inside
// the corpus text cannot break the TS source). Re-run after a fresh deep-audit corpus lands.
const fs = require('fs');
const path = require('path');

const repoRoot = path.resolve(__dirname, '..');
const corpusFile = process.argv[2] || path.join(repoRoot, 'docs', 'engine-context-corpus-2026-06-14.json');
const raw = JSON.parse(fs.readFileSync(corpusFile, 'utf8'));
const corpus = raw?.result?.corpus ?? raw?.corpus ?? raw;
if (!corpus || !corpus.improvedDossier) {
  throw new Error(`No corpus.improvedDossier found in ${corpusFile}`);
}

const lit = (v) => JSON.stringify(v);
const perApp = {};
for (const e of corpus.perAppContext || []) perApp[e.app] = e.context;

const out = `// AUTO-GENERATED by scripts/gen-context.js from the deep service-by-service audit corpus.
// Do NOT edit by hand. Source: ${path.basename(corpusFile)}. Re-run: node scripts/gen-context.js
/* eslint-disable */

export const IMPROVED_DOSSIER: string = ${lit(corpus.improvedDossier)};

export const PER_APP_CONTEXT: Record<string, string> = ${lit(perApp)};

export const NEW_GAME_PLAYBOOK: string = ${lit(corpus.newGamePlaybook || '')};

export const FEATURE_CATALOG: string = ${lit(corpus.featureCatalog || '')};

export const TARGET_APP_ENUM: readonly string[] = ${lit(corpus.targetAppEnum || [])};
`;

const dest = path.join(repoRoot, 'src', 'intel', 'generatedContext.ts');
fs.writeFileSync(dest, out, 'utf8');
console.log(`wrote ${dest} (${out.length} bytes; ${Object.keys(perApp).length} app blocks)`);
